name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v2

      - name: Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install dependencies ⚙️
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] build twine

      - name: Build the package 📦
        run: python -m build

      - name: Check the package 🧐
        run: python -m twine check dist/*

      - name: Release on PyPI 🎉
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

      - name: Build documentation with Sphinx 🐪
        run: |
          sphinx-build -b html docs _build

      - name: Deploy documentation 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          BRANCH: gh-pages
          FOLDER: _build
